services:
  server:
    build:
      context: .
    environment:
      PORT: 3000
      TOKEN_SECRET: secret
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    expose:
      - 3000
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drawing.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.drawing.entrypoints=web-secure"
      - "traefik.http.services.drawing.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    depends_on:
      - redis

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - default

volumes:
  redis_data:

networks:
  proxy:
    external: true
