services:
  server:
    build:
      context: .
    environment:
      PORT: 3000
      TOKEN_SECRET: secret
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.playlist-synchronizer.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.playlist-synchronizer.entrypoints=web-secure"
    depends_on:
      - redis

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  redis_data:

networks:
  proxy:
    external: true
