export const MAX_ROUNDS = 8;
export const RECONNECT_TIMEOUT = 5000;
export const ICE_GATHERING_TIMEOUT = 10000;
export const MAX_RECONNECT_ATTEMPTS = 3;
export const HEARTBEAT_INTERVAL = 10000;
export const RECREATE_OFFER_TIMEOUT = 1000;
